### PR TITLE
Enable Scheduled Jobs

### PR DESCRIPTION
**Pull request by wlan0**
https://github.com/rancher/rancher/issues/6120

NOTE: you need to use kubectl 1.4 to test this. (https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubectl)

@alena1108

### CODE REVIEW

**Comment by alena1108** [comment]
@wlan0 could you point to kubernetes issue that you filed for kubectl 1.4? The one about incorrect parsing. Want to check what subsequent 1.4 kubectl release have it, so we can use it in the template.

**Comment by wlan0** [comment]
https://github.com/kubernetes/kubernetes/issues/33588#issuecomment-250333870

That's the issue. It's not in kubectl 1.4.2, we have to wait for the next one.

**Comment by alena1108** [comment]
@wlan0 1.4.3 was released a day ago, could you check it?

**Comment by wlan0** [comment]
Checked it, unfortunately, the only tag associated with the fix for that issue is `v1.5.0-alpha.0-1756-g919bb01`

**Comment by deniseschannon** [comment]
@wlan0  Please make a new PR to the `1.2` branch when it's something that can be tested.

**Comment by weikinhuang** [comment]
Is this change going to go into `1.2`? This issue was closed without a follow up.

**Comment by alena1108** [comment]
@weikinhuang it will be in 1.2

**Comment by weikinhuang** [comment]
@alena1108 good to know, thanks!

**Pull request closed without merging**
